#!/usr/bin/env bash

# Script that installs Nginx server
sudo apt-get -y update
sudo apt-get -y install nginx

# Configure Nginx to return "Hello World!" at its root
echo "Hello World!" > /var/www/html/index.html

# Start Nginx service
sudo service nginx start
